Repository yetibot/yetibot, pull requests merged in 2019-04, with the labels that each got.

#815 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: in progress

#814 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: in progress

#813 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: in progress

#910 Add option to specify temps in C or F on weather
  src/yetibot/commands/weather.clj
  src/yetibot/commands/weather/formatters.clj
  test/yetibot/test/commands/weather.clj
Labels: in progress

#911 Jira error handling improvements
  src/yetibot/api/jira.clj
  src/yetibot/commands/jira.clj
Labels: in progress

#912 Log work on JIRA issue
  src/yetibot/api/jira.clj
  src/yetibot/commands/jira.clj
Labels: in progress

#907 826 fix weather parser
  src/yetibot/commands/weather.clj
  src/yetibot/models/postal_code.clj
Labels: in progress

#913 Jira create improvements
  src/yetibot/api/jira.clj
  src/yetibot/commands/jira.clj
Labels: in progress

#916 Add ability to specify reporter when creating jira issues
  src/yetibot/api/jira.clj
  src/yetibot/commands/jira.clj
Labels: jira

#917 Upgrade to yetibot.core 0.5.14 and fixup suppress references
  project.clj
  src/yetibot/commands/google.clj
  src/yetibot/commands/twitter.clj
Labels: in progress

#920 Pirate returns structured data
  src/yetibot/commands/pirate.clj
  test/yetibot/test/commands/pirate.clj
Labels: in progress

#921 Add conditions description to weather forecast
  src/yetibot/commands/weather.clj
  src/yetibot/commands/weather/formatters.clj
  test/yetibot/test/commands/weather.clj
Labels: in progress

#933 Get extended tweets when fetching user timeline
  src/yetibot/models/twitter.clj
Labels: twitter

#944 Fix data on clj when data is a lazy seq
  src/yetibot/commands/clojure.clj
Labels: in progress

#945 Fix clj data with nested seqs
  src/yetibot/commands/clojure.clj
  test/yetibot/test/commands/clojure.clj
Labels: in progress
